export const SERVICE_CHECKLISTS: Record<string, string[]> = {
  'Aircond cleaning': [
    'Clean air filters',
    'Clean evaporator coil',
    'Clean condenser coil',
    'Check and clear drain pipe',
    'Test cooling performance',
    'Clean unit exterior',
    'Check thermostat operation',
  ],
  'Aircond repair': [
    'Diagnose reported fault',
    'Replace faulty component',
    'Test unit operation after repair',
    'Check refrigerant pressure',
    'Verify electrical connections',
    'Clean accessible parts',
  ],
  'Gas refill': [
    'Check for refrigerant leaks',
    'Evacuate old refrigerant',
    'Vacuum system',
    'Refill refrigerant to specification',
    'Test cooling after refill',
    'Record final pressure readings',
  ],
  'Installation': [
    'Site inspection and measurement',
    'Mount indoor unit with bracket',
    'Mount outdoor unit on pad/bracket',
    'Connect refrigerant piping',
    'Connect electrical wiring',
    'Vacuum and pressure test',
    'Test run all modes',
    'Explain operation to customer',
  ],
  'Inspection': [
    'Visual inspection of indoor unit',
    'Visual inspection of outdoor unit',
    'Check refrigerant pressure',
    'Inspect electrical connections',
    'Clean or replace filters as needed',
    'Test cooling and heating',
    'Provide condition report',
  ],
}
